-- ============================================================
-- VARS PMC Demo — initial schema bootstrap
-- Generated by concatenating supabase/migrations/0001..0015.sql
-- Paste this file in one go into the SQL editor of the demo
-- Supabase project, then click Run.
-- ============================================================

-- ============================================================
-- 0001_schemas_and_extensions.sql
-- ============================================================
-- Snapshot of the VARS-PMC Supabase project (ref: khhguxuxvkxvycndkron) as of 2026-05-23.
-- Reproduces the live schema, indexes, RLS policies, helper functions, and storage
-- buckets so the database can be rebuilt from this repo. Apply files in numeric order.

-- ---------------------------------------------------------------------------
-- Extensions and schemas
-- ---------------------------------------------------------------------------

-- Helper schema for SECURITY DEFINER functions used by RLS policies. Keeping
-- them out of `public` so they cannot be called directly from the PostgREST API.
CREATE SCHEMA IF NOT EXISTS private;

-- gen_random_uuid() comes from pgcrypto, which Supabase ships with by default.
-- Listed here for completeness in case the project is rebuilt elsewhere.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 0002_tables.sql
-- ============================================================
-- All public-schema tables for VARS-PMC.
-- Created in FK-dependency order: a table only references tables defined above it.

-- ---------------------------------------------------------------------------
-- buildings: physical properties under management
-- ---------------------------------------------------------------------------
CREATE TABLE public.buildings (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL UNIQUE,
  address     text,
  notes       text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- units: individual apartments / flats inside a building
-- ---------------------------------------------------------------------------
CREATE TABLE public.units (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  building_id  uuid NOT NULL REFERENCES public.buildings(id) ON DELETE CASCADE,
  floor        integer NOT NULL,
  unit_number  text NOT NULL,
  notes        text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (building_id, unit_number)
);

-- ---------------------------------------------------------------------------
-- profiles: one row per auth.users account; carries app-level metadata
-- ---------------------------------------------------------------------------
CREATE TABLE public.profiles (
  id               uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name        text NOT NULL,
  phone            text,
  role             text NOT NULL CHECK (role = ANY (ARRAY['pmc'::text, 'resident'::text, 'security'::text])),
  date_of_birth    date,
  passport_number  text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- resident_assignments: which profile lives in which unit, with lease info
-- ---------------------------------------------------------------------------
CREATE TABLE public.resident_assignments (
  profile_id           uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  unit_id              uuid NOT NULL REFERENCES public.units(id) ON DELETE RESTRICT,
  tenure               text CHECK (tenure = ANY (ARRAY['Owner'::text, 'Tenant'::text])),
  lease_start          date,
  lease_end            date,
  monthly_payment_aed  numeric CHECK (monthly_payment_aed IS NULL OR monthly_payment_aed >= 0),
  ownership_start      date,
  assigned_at          timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- security_assignments: which guard covers which building on which shift
-- ---------------------------------------------------------------------------
CREATE TABLE public.security_assignments (
  profile_id   uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  building_id  uuid NOT NULL REFERENCES public.buildings(id) ON DELETE RESTRICT,
  shift        text NOT NULL CHECK (shift = ANY (ARRAY['Day'::text, 'Night'::text, '24h'::text])),
  assigned_at  timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- visits: replacement for legacy data.visitors / data.entryLog / data.pendingApprovals
-- ---------------------------------------------------------------------------
CREATE TABLE public.visits (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id         uuid NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  type            text NOT NULL CHECK (type = ANY (ARRAY['Pre-Approved'::text, 'Walk-In'::text, 'Delivery'::text, 'Service Vendor'::text, 'Resident Guest'::text, 'Contractor'::text])),
  visitor_name    text NOT NULL,
  visitor_phone   text,
  visitor_id_doc  text,
  vehicle         text,
  purpose         text,
  notes           text,
  visit_date      date NOT NULL,
  visit_time      time,
  status          text NOT NULL DEFAULT 'Pre-Approved' CHECK (status = ANY (ARRAY['Pre-Approved'::text, 'On-Premise'::text, 'Checked-Out'::text, 'Rejected'::text, 'No-Show'::text, 'Cancelled'::text])),
  permit_ref      text,
  qr_code         text,
  created_by      uuid REFERENCES public.profiles(id),
  approved_by     uuid REFERENCES public.profiles(id),
  checked_in_at   timestamptz,
  checked_out_at  timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- unit_attachments: metadata for files in the `unit-attachments` storage bucket
-- ---------------------------------------------------------------------------
CREATE TABLE public.unit_attachments (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id       uuid NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  kind          text NOT NULL CHECK (kind = ANY (ARRAY['photo'::text, 'title_deed'::text, 'layout'::text, 'other'::text])),
  filename      text NOT NULL,
  storage_path  text NOT NULL,
  uploaded_by   uuid REFERENCES public.profiles(id),
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- amenity_bookings: pool / gym / function-room reservations
-- ---------------------------------------------------------------------------
CREATE TABLE public.amenity_bookings (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  building_id          uuid NOT NULL REFERENCES public.buildings(id) ON DELETE CASCADE,
  unit_id              uuid REFERENCES public.units(id) ON DELETE SET NULL,
  resident_profile_id  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  amenity_name         text NOT NULL,
  booking_date         date NOT NULL,
  start_time           time,
  end_time             time,
  guests               integer DEFAULT 0,
  status               text NOT NULL DEFAULT 'Confirmed' CHECK (status = ANY (ARRAY['Confirmed'::text, 'Pending'::text, 'Cancelled'::text, 'Completed'::text])),
  notes                text,
  created_at           timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- service_requests: maintenance / housekeeping / repair tickets
-- ---------------------------------------------------------------------------
CREATE TABLE public.service_requests (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id              uuid REFERENCES public.units(id) ON DELETE SET NULL,
  resident_profile_id  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  category             text NOT NULL,
  description          text NOT NULL,
  priority             text NOT NULL DEFAULT 'Normal' CHECK (priority = ANY (ARRAY['Low'::text, 'Normal'::text, 'High'::text, 'Urgent'::text])),
  status               text NOT NULL DEFAULT 'New' CHECK (status = ANY (ARRAY['New'::text, 'Acknowledged'::text, 'In Progress'::text, 'Done'::text, 'Closed'::text, 'Rejected'::text])),
  preferred_date       date,
  preferred_time       time,
  resolved_at          timestamptz,
  notes                text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- invoices: service-charge and ad-hoc bills issued to residents
-- ---------------------------------------------------------------------------
CREATE TABLE public.invoices (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id              uuid NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  resident_profile_id  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  invoice_number       text UNIQUE,
  description          text NOT NULL,
  amount_aed           numeric NOT NULL CHECK (amount_aed >= 0),
  due_date             date,
  status               text NOT NULL DEFAULT 'Pending' CHECK (status = ANY (ARRAY['Pending'::text, 'Paid'::text, 'Overdue'::text, 'Cancelled'::text])),
  source_type          text,
  source_id            uuid,
  notes                text,
  created_at           timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- payments: money received against an invoice
-- ---------------------------------------------------------------------------
CREATE TABLE public.payments (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id  uuid NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  amount_aed  numeric NOT NULL CHECK (amount_aed > 0),
  paid_at     timestamptz NOT NULL DEFAULT now(),
  method      text NOT NULL DEFAULT 'manual' CHECK (method = ANY (ARRAY['manual'::text, 'card'::text, 'bank_transfer'::text, 'cash'::text])),
  reference   text,
  notes       text,
  created_by  uuid REFERENCES public.profiles(id),
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- resident_documents: metadata for files in the `resident-documents` bucket
-- ---------------------------------------------------------------------------
CREATE TABLE public.resident_documents (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  kind          text NOT NULL CHECK (kind = ANY (ARRAY['emirates_id'::text, 'passport'::text, 'tenancy_contract'::text, 'owning_contract'::text, 'title_deed'::text, 'other'::text])),
  filename      text NOT NULL,
  storage_path  text NOT NULL,
  uploaded_by   uuid REFERENCES public.profiles(id),
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- app_state: legacy single-row jsonb store driving the older Resident /
-- Security / PM views. Being phased out slice by slice in favour of the
-- relational tables above. Kept for backward compatibility with the running app.
-- ---------------------------------------------------------------------------
CREATE TABLE public.app_state (
  id          text PRIMARY KEY,
  data        jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 0003_indexes.sql
-- ============================================================
-- Non-PK indexes for the public-schema tables.
-- Most exist to make foreign-key joins cheap; a handful index status / date
-- columns used by the dashboard filters.

CREATE INDEX amenity_bookings_building_idx  ON public.amenity_bookings (building_id);
CREATE INDEX amenity_bookings_date_idx      ON public.amenity_bookings (booking_date);
CREATE INDEX amenity_bookings_resident_idx  ON public.amenity_bookings (resident_profile_id);

CREATE INDEX invoices_resident_idx          ON public.invoices (resident_profile_id);
CREATE INDEX invoices_status_idx            ON public.invoices (status);
CREATE INDEX invoices_unit_idx              ON public.invoices (unit_id);

CREATE INDEX payments_invoice_idx           ON public.payments (invoice_id);

CREATE INDEX resident_assignments_unit_id_idx ON public.resident_assignments (unit_id);

CREATE INDEX resident_documents_profile_idx ON public.resident_documents (profile_id);

CREATE INDEX security_assignments_building_id_idx ON public.security_assignments (building_id);

CREATE INDEX service_requests_resident_idx ON public.service_requests (resident_profile_id);
CREATE INDEX service_requests_status_idx   ON public.service_requests (status);
CREATE INDEX service_requests_unit_idx     ON public.service_requests (unit_id);

CREATE INDEX unit_attachments_unit_id_idx  ON public.unit_attachments (unit_id);

CREATE INDEX units_building_id_idx         ON public.units (building_id);

CREATE INDEX visits_status_idx             ON public.visits (status);
CREATE INDEX visits_unit_id_idx            ON public.visits (unit_id);
CREATE INDEX visits_visit_date_idx         ON public.visits (visit_date);

-- ============================================================
-- 0004_helper_functions.sql
-- ============================================================
-- SECURITY DEFINER helper functions in the `private` schema. RLS policies on
-- public.* tables call these to avoid the infinite-recursion trap you hit when
-- a policy on table X subqueries table Y whose policy in turn subqueries X.
-- All of them are STABLE, run with the function owner's permissions, and have
-- search_path locked to '' so an attacker cannot shadow public tables.

-- --- private schema helpers --------------------------------------------------

CREATE OR REPLACE FUNCTION private.is_resident_of_unit(p_profile_id uuid, p_unit_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.resident_assignments
    WHERE profile_id = p_profile_id AND unit_id = p_unit_id
  );
$$;

CREATE OR REPLACE FUNCTION private.is_resident_of_building(p_profile_id uuid, p_building_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.resident_assignments ra
    JOIN public.units u ON u.id = ra.unit_id
    WHERE ra.profile_id = p_profile_id AND u.building_id = p_building_id
  );
$$;

CREATE OR REPLACE FUNCTION private.is_security_of_building(p_profile_id uuid, p_building_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.security_assignments
    WHERE profile_id = p_profile_id AND building_id = p_building_id
  );
$$;

CREATE OR REPLACE FUNCTION private.security_can_see_resident(p_security_id uuid, p_resident_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.resident_assignments ra
    JOIN public.units                u  ON u.id = ra.unit_id
    JOIN public.security_assignments sa ON sa.building_id = u.building_id
    WHERE ra.profile_id = p_resident_id AND sa.profile_id = p_security_id
  );
$$;

CREATE OR REPLACE FUNCTION private.unit_building_id(p_unit_id uuid)
RETURNS uuid
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT building_id FROM public.units WHERE id = p_unit_id;
$$;

CREATE OR REPLACE FUNCTION private.user_id_by_email(p_email text)
RETURNS uuid
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT id FROM auth.users WHERE lower(email) = lower(p_email) LIMIT 1;
$$;

-- --- public schema helper ----------------------------------------------------

-- Returns auth.users.email for the given profile IDs, but only when the caller
-- has app_metadata.role = 'pmc'. PostgREST cannot reach auth.users directly, so
-- the PMC admin UI calls this RPC to display resident / guard email addresses.
CREATE OR REPLACE FUNCTION public.get_emails_for_profiles(p_ids uuid[])
RETURNS TABLE(id uuid, email text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  IF COALESCE((auth.jwt() -> 'app_metadata' ->> 'role'), '') <> 'pmc' THEN
    RETURN;
  END IF;
  RETURN QUERY SELECT u.id, u.email::text FROM auth.users u WHERE u.id = ANY(p_ids);
END;
$$;

-- ============================================================
-- 0005_rls_policies.sql
-- ============================================================
-- Row-Level Security for every public table.
--
-- Naming convention: <role>_<table>_<action>. The PMC role gets full access
-- via a single ALL policy; residents and security see only their own rows
-- (or rows scoped to their assigned unit / building) via the SECURITY DEFINER
-- helpers in the `private` schema.
--
-- Policies key off auth.jwt()->'app_metadata'->>'role' (NOT a subquery against
-- public.profiles) to avoid infinite recursion. When creating an auth.users row,
-- ALWAYS set app_metadata.role — a NULL role hits every PMC policy as 'not pmc'.

-- ---------------------------------------------------------------------------
-- Enable RLS on every table
-- ---------------------------------------------------------------------------
ALTER TABLE public.app_state             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buildings             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resident_assignments  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_assignments  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visits                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unit_attachments      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amenity_bookings      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_requests      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resident_documents    ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- app_state — single 'main' row, open to anon + authenticated (legacy)
-- ---------------------------------------------------------------------------
CREATE POLICY "Allow read of main row"
  ON public.app_state FOR SELECT TO anon, authenticated
  USING (id = 'main');

CREATE POLICY "Allow insert of main row"
  ON public.app_state FOR INSERT TO anon, authenticated
  WITH CHECK (id = 'main');

CREATE POLICY "Allow update of main row"
  ON public.app_state FOR UPDATE TO anon, authenticated
  USING (id = 'main') WITH CHECK (id = 'main');

-- ---------------------------------------------------------------------------
-- buildings
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_buildings_all
  ON public.buildings FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_buildings_read_own
  ON public.buildings FOR SELECT TO authenticated
  USING (private.is_resident_of_building(auth.uid(), id));

CREATE POLICY security_buildings_read_assigned
  ON public.buildings FOR SELECT TO authenticated
  USING (private.is_security_of_building(auth.uid(), id));

-- ---------------------------------------------------------------------------
-- units
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_units_all
  ON public.units FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_units_read_own
  ON public.units FOR SELECT TO authenticated
  USING (private.is_resident_of_unit(auth.uid(), id));

CREATE POLICY security_units_read_assigned_building
  ON public.units FOR SELECT TO authenticated
  USING (private.is_security_of_building(auth.uid(), building_id));

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_profiles_all
  ON public.profiles FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY any_user_read_own_profile
  ON public.profiles FOR SELECT TO authenticated
  USING (id = auth.uid());

CREATE POLICY any_user_update_own_profile
  ON public.profiles FOR UPDATE TO authenticated
  USING (id = auth.uid()) WITH CHECK (id = auth.uid());

CREATE POLICY security_read_residents_in_building
  ON public.profiles FOR SELECT TO authenticated
  USING (private.security_can_see_resident(auth.uid(), id));

-- ---------------------------------------------------------------------------
-- resident_assignments
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_resident_assignments_all
  ON public.resident_assignments FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_read_own_assignment
  ON public.resident_assignments FOR SELECT TO authenticated
  USING (profile_id = auth.uid());

CREATE POLICY security_read_assignments_in_building
  ON public.resident_assignments FOR SELECT TO authenticated
  USING (private.is_security_of_building(auth.uid(), private.unit_building_id(unit_id)));

-- ---------------------------------------------------------------------------
-- security_assignments
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_security_assignments_all
  ON public.security_assignments FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY security_read_own_assignment
  ON public.security_assignments FOR SELECT TO authenticated
  USING (profile_id = auth.uid());

-- ---------------------------------------------------------------------------
-- visits
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_visits_all
  ON public.visits FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_visits_read_own
  ON public.visits FOR SELECT TO authenticated
  USING (private.is_resident_of_unit(auth.uid(), unit_id));

CREATE POLICY resident_visits_insert_own
  ON public.visits FOR INSERT TO authenticated
  WITH CHECK (private.is_resident_of_unit(auth.uid(), unit_id));

CREATE POLICY resident_visits_update_own
  ON public.visits FOR UPDATE TO authenticated
  USING      (private.is_resident_of_unit(auth.uid(), unit_id))
  WITH CHECK (private.is_resident_of_unit(auth.uid(), unit_id));

CREATE POLICY security_visits_read_building
  ON public.visits FOR SELECT TO authenticated
  USING (private.is_security_of_building(auth.uid(), private.unit_building_id(unit_id)));

CREATE POLICY security_visits_update_building
  ON public.visits FOR UPDATE TO authenticated
  USING      (private.is_security_of_building(auth.uid(), private.unit_building_id(unit_id)))
  WITH CHECK (private.is_security_of_building(auth.uid(), private.unit_building_id(unit_id)));

-- ---------------------------------------------------------------------------
-- unit_attachments
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_attachments_all
  ON public.unit_attachments FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_attachments_read_own
  ON public.unit_attachments FOR SELECT TO authenticated
  USING (private.is_resident_of_unit(auth.uid(), unit_id));

CREATE POLICY security_attachments_read_building
  ON public.unit_attachments FOR SELECT TO authenticated
  USING (private.is_security_of_building(auth.uid(), private.unit_building_id(unit_id)));

-- ---------------------------------------------------------------------------
-- amenity_bookings
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_amenity_all
  ON public.amenity_bookings FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_amenity_read_building
  ON public.amenity_bookings FOR SELECT TO authenticated
  USING (private.is_resident_of_building(auth.uid(), building_id));

CREATE POLICY resident_amenity_insert_own
  ON public.amenity_bookings FOR INSERT TO authenticated
  WITH CHECK (resident_profile_id = auth.uid());

CREATE POLICY resident_amenity_update_own
  ON public.amenity_bookings FOR UPDATE TO authenticated
  USING      (resident_profile_id = auth.uid())
  WITH CHECK (resident_profile_id = auth.uid());

CREATE POLICY security_amenity_read_building
  ON public.amenity_bookings FOR SELECT TO authenticated
  USING (private.is_security_of_building(auth.uid(), building_id));

-- ---------------------------------------------------------------------------
-- service_requests
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_sr_all
  ON public.service_requests FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_sr_read_own
  ON public.service_requests FOR SELECT TO authenticated
  USING (resident_profile_id = auth.uid());

CREATE POLICY resident_sr_insert_own
  ON public.service_requests FOR INSERT TO authenticated
  WITH CHECK (resident_profile_id = auth.uid());

CREATE POLICY resident_sr_update_own_pending
  ON public.service_requests FOR UPDATE TO authenticated
  USING      ((resident_profile_id = auth.uid()) AND (status = ANY (ARRAY['New'::text, 'Acknowledged'::text])))
  WITH CHECK (resident_profile_id = auth.uid());

-- ---------------------------------------------------------------------------
-- invoices
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_invoices_all
  ON public.invoices FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_invoices_read_own
  ON public.invoices FOR SELECT TO authenticated
  USING (resident_profile_id = auth.uid());

-- ---------------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_payments_all
  ON public.payments FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_payments_read_own
  ON public.payments FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.invoices i
    WHERE i.id = payments.invoice_id AND i.resident_profile_id = auth.uid()
  ));

-- ---------------------------------------------------------------------------
-- resident_documents
-- ---------------------------------------------------------------------------
CREATE POLICY pmc_resident_docs_all
  ON public.resident_documents FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_docs_read_own
  ON public.resident_documents FOR SELECT TO authenticated
  USING (profile_id = auth.uid());

-- ============================================================
-- 0006_storage.sql
-- ============================================================
-- Storage buckets + RLS policies on storage.objects.
--
-- Two private buckets:
--   • unit-attachments   — photos, title deeds, floor plans per unit.
--                          Path convention: {unit_id}/{filename}
--   • resident-documents — emirates ID, passport, tenancy contracts, etc.
--                          Path convention: {profile_id}/{filename}
--
-- Both buckets are private; the app uses signed URLs to serve files.

INSERT INTO storage.buckets (id, name, public)
VALUES ('unit-attachments',   'unit-attachments',   false),
       ('resident-documents', 'resident-documents', false)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Policies on storage.objects
-- ---------------------------------------------------------------------------
-- PMC has full access to both buckets. Residents read only files under their
-- own folder (first path segment matches their unit_id or profile id).
-- Security reads only files under units in their assigned building(s).

CREATE POLICY pmc_storage_all
  ON storage.objects FOR ALL TO authenticated
  USING ((bucket_id = 'unit-attachments')
         AND ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc'))
  WITH CHECK ((bucket_id = 'unit-attachments')
              AND ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc'));

CREATE POLICY pmc_resident_storage_all
  ON storage.objects FOR ALL TO authenticated
  USING ((bucket_id = 'resident-documents')
         AND ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc'))
  WITH CHECK ((bucket_id = 'resident-documents')
              AND ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc'));

CREATE POLICY resident_storage_read_own
  ON storage.objects FOR SELECT TO authenticated
  USING ((bucket_id = 'unit-attachments')
         AND private.is_resident_of_unit(auth.uid(), ((storage.foldername(name))[1])::uuid));

CREATE POLICY security_storage_read_building
  ON storage.objects FOR SELECT TO authenticated
  USING ((bucket_id = 'unit-attachments')
         AND private.is_security_of_building(
               auth.uid(),
               private.unit_building_id(((storage.foldername(name))[1])::uuid)
             ));

CREATE POLICY resident_docs_storage_read_own
  ON storage.objects FOR SELECT TO authenticated
  USING ((bucket_id = 'resident-documents')
         AND ((storage.foldername(name))[1])::uuid = auth.uid());

-- ============================================================
-- 0007_vendors.sql
-- ============================================================
-- VARS-PMC: maintenance vendors + contracts + payments + documents
-- Adds the relational tables, a private Storage bucket for contract files,
-- and PMC-only RLS policies. Residents and security have no access.

-- ---------------------------------------------------------------------------
-- vendors: master record per maintenance company
-- ---------------------------------------------------------------------------
CREATE TABLE public.vendors (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name                text NOT NULL,
  service_category    text NOT NULL CHECK (service_category = ANY (ARRAY[
                        'Plumbing','Electrical','HVAC','Cleaning','Security',
                        'Gardening','Pest Control','Lift Maintenance',
                        'General Handyman','Other'
                      ])),
  contact_person      text,
  contact_phone       text,
  contact_email       text,
  address             text,
  contract_start      date,
  contract_end        date,
  contract_value_aed  numeric CHECK (contract_value_aed IS NULL OR contract_value_aed >= 0),
  trade_license       text,
  trn_number          text,
  status              text NOT NULL DEFAULT 'Active' CHECK (status = ANY (ARRAY[
                        'Active','Expiring Soon','Expired','Terminated'
                      ])),
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX vendors_service_category_idx ON public.vendors (service_category);
CREATE INDEX vendors_status_idx           ON public.vendors (status);

-- ---------------------------------------------------------------------------
-- vendor_buildings: M2M — which of your buildings each vendor services
-- ---------------------------------------------------------------------------
CREATE TABLE public.vendor_buildings (
  vendor_id    uuid NOT NULL REFERENCES public.vendors(id)   ON DELETE CASCADE,
  building_id  uuid NOT NULL REFERENCES public.buildings(id) ON DELETE CASCADE,
  PRIMARY KEY (vendor_id, building_id)
);
CREATE INDEX vendor_buildings_building_idx ON public.vendor_buildings (building_id);

-- ---------------------------------------------------------------------------
-- vendor_payments: invoices issued by the vendor + payments tracked
-- ---------------------------------------------------------------------------
CREATE TABLE public.vendor_payments (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id          uuid NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE,
  invoice_number     text,
  invoice_date       date,
  description        text NOT NULL,
  category           text,
  amount_aed         numeric NOT NULL CHECK (amount_aed >= 0),
  payment_status     text NOT NULL DEFAULT 'Pending' CHECK (payment_status = ANY (ARRAY[
                       'Pending','Paid','Overdue','Cancelled'
                     ])),
  paid_date          date,
  payment_method     text CHECK (payment_method IS NULL OR payment_method = ANY (ARRAY[
                       'Bank Transfer','Cheque','Cash','Credit Card','Other'
                     ])),
  payment_reference  text,
  notes              text,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX vendor_payments_vendor_idx       ON public.vendor_payments (vendor_id);
CREATE INDEX vendor_payments_status_idx       ON public.vendor_payments (payment_status);
CREATE INDEX vendor_payments_invoice_date_idx ON public.vendor_payments (invoice_date);

-- ---------------------------------------------------------------------------
-- vendor_documents: metadata for files in the `maintenance-documents` bucket
-- ---------------------------------------------------------------------------
CREATE TABLE public.vendor_documents (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id     uuid NOT NULL REFERENCES public.vendors(id)         ON DELETE CASCADE,
  payment_id    uuid          REFERENCES public.vendor_payments(id) ON DELETE SET NULL,
  kind          text NOT NULL CHECK (kind = ANY (ARRAY['contract','payment_receipt','invoice','other'])),
  filename      text NOT NULL,
  storage_path  text NOT NULL,
  uploaded_by   uuid REFERENCES public.profiles(id),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX vendor_documents_vendor_idx ON public.vendor_documents (vendor_id);

-- ---------------------------------------------------------------------------
-- Storage bucket (private, PMC-only)
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('maintenance-documents', 'maintenance-documents', false)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- RLS: PMC has full access on all four new tables. Nobody else.
-- Policies key off auth.jwt()->'app_metadata'->>'role' to avoid recursion.
-- ---------------------------------------------------------------------------
ALTER TABLE public.vendors           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_buildings  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_payments   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_documents  ENABLE ROW LEVEL SECURITY;

CREATE POLICY pmc_vendors_all
  ON public.vendors FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY pmc_vendor_buildings_all
  ON public.vendor_buildings FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY pmc_vendor_payments_all
  ON public.vendor_payments FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY pmc_vendor_documents_all
  ON public.vendor_documents FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

-- Storage policy: PMC has full access to the new bucket. No resident/security policy.
CREATE POLICY pmc_maintenance_storage_all
  ON storage.objects FOR ALL TO authenticated
  USING      ((bucket_id = 'maintenance-documents')
              AND ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc'))
  WITH CHECK ((bucket_id = 'maintenance-documents')
              AND ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc'));

-- ============================================================
-- 0008_resident_extras.sql
-- ============================================================
-- Add extra tenant-facing fields to public.profiles for the one-page
-- Resident Statement view + bulk-upload template additions.
--
-- All fields are nullable so existing rows continue to work. PII access
-- is governed by the existing profiles RLS policies (PMC sees all,
-- residents see their own row, security sees residents in their building).

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS emirates_id              text,
  ADD COLUMN IF NOT EXISTS emergency_contact_name   text,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone  text,
  ADD COLUMN IF NOT EXISTS employer                 text,
  ADD COLUMN IF NOT EXISTS occupation               text;

COMMENT ON COLUMN public.profiles.emirates_id IS 'UAE Emirates ID number, e.g. 784-1985-1234567-8.';
COMMENT ON COLUMN public.profiles.emergency_contact_name  IS 'Name of next-of-kin / emergency contact.';
COMMENT ON COLUMN public.profiles.emergency_contact_phone IS 'Phone for the emergency contact.';
COMMENT ON COLUMN public.profiles.employer    IS 'Employer name (optional, used for tenancy compliance).';
COMMENT ON COLUMN public.profiles.occupation  IS 'Job title / occupation (optional).';

-- ============================================================
-- 0009_invoice_attachments.sql
-- ============================================================
-- Invoice attachments — one row per file attached to an invoice.
--
-- Each invoice can carry up to TWO attachments:
--   • kind = 'invoice'        → the issued invoice PDF / image
--   • kind = 'payment_proof'  → bank receipt / cheque image / proof of payment
-- The (invoice_id, kind) UNIQUE constraint enforces "max one of each kind".
--
-- Files live in the private Storage bucket `invoice-attachments` under the
-- path convention `{invoice_id}/{kind}/{filename}`. We store the storage_path
-- on the row so the frontend can issue signed URLs without round-tripping
-- the bucket index.
--
-- RLS:
--   • PMC has full access.
--   • Residents can SELECT only attachments tied to invoices billed to them.
--   • Security cannot see invoice attachments at all (financial PII).
--
-- The resident check goes through a SECURITY DEFINER helper in `private`
-- to keep the RLS policy free of cross-table subqueries (avoids the
-- recursion trap that bit us before — see memory).

-- ---------------------------------------------------------------------------
-- 1. Table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.invoice_attachments (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id    uuid NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  kind          text NOT NULL CHECK (kind = ANY (ARRAY['invoice'::text, 'payment_proof'::text])),
  storage_path  text NOT NULL,
  file_name     text NOT NULL,
  mime_type     text,
  size_bytes    bigint,
  uploaded_by   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  uploaded_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (invoice_id, kind)
);

CREATE INDEX IF NOT EXISTS invoice_attachments_invoice_id_idx
  ON public.invoice_attachments(invoice_id);

COMMENT ON TABLE  public.invoice_attachments         IS 'Files attached to invoices: the issued invoice PDF and the payment proof.';
COMMENT ON COLUMN public.invoice_attachments.kind          IS 'Which slot this file fills: ''invoice'' or ''payment_proof''.';
COMMENT ON COLUMN public.invoice_attachments.storage_path  IS 'Object key in the `invoice-attachments` bucket. Convention: {invoice_id}/{kind}/{filename}.';
COMMENT ON COLUMN public.invoice_attachments.uploaded_by   IS 'Profile id of whoever uploaded the file (PMC user).';

-- ---------------------------------------------------------------------------
-- 2. Private helper — resident-of-invoice check
-- ---------------------------------------------------------------------------
-- SECURITY DEFINER so RLS on public.invoices is bypassed when checking
-- ownership from the invoice_attachments / storage policies. Pure read,
-- STABLE so the planner can cache results within a statement.
CREATE OR REPLACE FUNCTION private.is_resident_of_invoice(_user uuid, _invoice_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.invoices
    WHERE id = _invoice_id
      AND resident_profile_id = _user
  );
$$;

REVOKE ALL ON FUNCTION private.is_resident_of_invoice(uuid, uuid) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION private.is_resident_of_invoice(uuid, uuid) TO authenticated;

COMMENT ON FUNCTION private.is_resident_of_invoice(uuid, uuid)
  IS 'True if the given user is the resident billed on the given invoice. Used by RLS to avoid inlining a cross-table subquery into invoice_attachments / storage policies.';

-- ---------------------------------------------------------------------------
-- 3. Enable RLS + policies on public.invoice_attachments
-- ---------------------------------------------------------------------------
ALTER TABLE public.invoice_attachments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pmc_invoice_attachments_all      ON public.invoice_attachments;
DROP POLICY IF EXISTS resident_invoice_attachments_ro  ON public.invoice_attachments;

CREATE POLICY pmc_invoice_attachments_all
  ON public.invoice_attachments FOR ALL TO authenticated
  USING      ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc')
  WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc');

CREATE POLICY resident_invoice_attachments_ro
  ON public.invoice_attachments FOR SELECT TO authenticated
  USING (private.is_resident_of_invoice(auth.uid(), invoice_id));

-- ---------------------------------------------------------------------------
-- 4. Storage bucket + storage.objects policies
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('invoice-attachments', 'invoice-attachments', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS pmc_invoice_attach_storage_all       ON storage.objects;
DROP POLICY IF EXISTS resident_invoice_attach_storage_ro   ON storage.objects;

CREATE POLICY pmc_invoice_attach_storage_all
  ON storage.objects FOR ALL TO authenticated
  USING ((bucket_id = 'invoice-attachments')
         AND ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc'))
  WITH CHECK ((bucket_id = 'invoice-attachments')
              AND ((auth.jwt() -> 'app_metadata' ->> 'role') = 'pmc'));

-- First path segment is the invoice_id (see storage_path convention above).
CREATE POLICY resident_invoice_attach_storage_ro
  ON storage.objects FOR SELECT TO authenticated
  USING ((bucket_id = 'invoice-attachments')
         AND private.is_resident_of_invoice(
               auth.uid(),
               ((storage.foldername(name))[1])::uuid
             ));

-- ============================================================
-- 0010_invoice_attachments_multiple.sql
-- ============================================================
-- Allow multiple files per invoice attachment slot.
--
-- Migration 0009 added a UNIQUE (invoice_id, kind) constraint so each
-- invoice could hold at most one 'invoice' file and one 'payment_proof'
-- file. The product decision changed: PMC may legitimately attach
-- several files per slot (e.g. multi-page scans, separate cheque images,
-- partial-payment receipts). The vendor side (vendor_documents) already
-- allows this — this migration brings the resident side in line.
--
-- Dropping the constraint is safe: it does not touch existing rows.

ALTER TABLE public.invoice_attachments
  DROP CONSTRAINT IF EXISTS invoice_attachments_invoice_id_kind_key;

-- ============================================================
-- 0011_property_type_commercial_land.sql
-- ============================================================
-- Add 'Commercial Land' as a fourth allowed property_type.
--
-- The original check (migration 0007) restricted property_type to
-- Residential / Commercial / Villa. Commercial Land is for raw plots
-- that are leased / managed but have no building structure on them
-- yet (no floors, no units, just the land record).
--
-- Drop the old constraint and recreate with the new enum.

ALTER TABLE public.buildings
  DROP CONSTRAINT IF EXISTS buildings_property_type_check;

ALTER TABLE public.buildings
  ADD CONSTRAINT buildings_property_type_check
  CHECK (property_type = ANY (ARRAY[
    'Residential'::text,
    'Commercial'::text,
    'Villa'::text,
    'Commercial Land'::text
  ]));

-- ============================================================
-- 0012_units_owner_fields.sql
-- ============================================================
-- Each unit now carries its own Owner record (the property owner) alongside
-- the resident assignment. The owner is conceptually permanent and survives
-- tenant turnover; the resident assignment can change over time.
--
-- owner_is_resident flags units where the resident IS the owner — used by
-- the UI to render a 'Same as resident' chip rather than duplicating the
-- fields on screen.

ALTER TABLE public.units
  ADD COLUMN IF NOT EXISTS owner_name             text,
  ADD COLUMN IF NOT EXISTS owner_phone            text,
  ADD COLUMN IF NOT EXISTS owner_email            text,
  ADD COLUMN IF NOT EXISTS owner_passport_number  text,
  ADD COLUMN IF NOT EXISTS owner_emirates_id      text,
  ADD COLUMN IF NOT EXISTS purchase_date          date,
  ADD COLUMN IF NOT EXISTS owner_is_resident      boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.units.owner_name        IS 'Full legal name of the unit owner.';
COMMENT ON COLUMN public.units.owner_phone       IS 'Primary phone for the owner (for invoicing / disputes).';
COMMENT ON COLUMN public.units.owner_email       IS 'Email for the owner.';
COMMENT ON COLUMN public.units.owner_passport_number IS 'Passport number of the owner.';
COMMENT ON COLUMN public.units.owner_emirates_id IS 'UAE Emirates ID of the owner.';
COMMENT ON COLUMN public.units.purchase_date     IS 'Date the owner acquired the unit.';
COMMENT ON COLUMN public.units.owner_is_resident IS 'true when the resident assignment IS the owner — the UI then shows a same-as chip instead of duplicating the fields.';

-- ============================================================
-- 0013_units_tenant_fields.sql
-- ============================================================
-- Non-residential property types (Commercial, Villa, Commercial Land) do NOT
-- create Supabase Auth users for their tenants / clients / villa residents.
-- We still need a place to record the contact info that comes in via the
-- bulk-upload spreadsheet, so add denormalised tenant/* columns to units.
--
-- Residential keeps using profiles + resident_assignments + auth.users.
ALTER TABLE public.units
  ADD COLUMN IF NOT EXISTS tenant_name          text,
  ADD COLUMN IF NOT EXISTS tenant_email         text,
  ADD COLUMN IF NOT EXISTS tenant_phone         text,
  ADD COLUMN IF NOT EXISTS tenant_tenure        text,
  ADD COLUMN IF NOT EXISTS tenant_contract_number text,
  ADD COLUMN IF NOT EXISTS tenant_lease_start   date,
  ADD COLUMN IF NOT EXISTS tenant_lease_end     date,
  ADD COLUMN IF NOT EXISTS tenant_monthly_payment_aed numeric;

COMMENT ON COLUMN public.units.tenant_name          IS 'Non-residential tenant/client/villa-resident display name (denormalised on the unit; no Auth account).';
COMMENT ON COLUMN public.units.tenant_email         IS 'Non-residential tenant/client/villa-resident contact email.';
COMMENT ON COLUMN public.units.tenant_phone         IS 'Non-residential tenant/client/villa-resident contact phone.';
COMMENT ON COLUMN public.units.tenant_tenure        IS 'Owner | Tenant (mirrors resident_assignments.tenure semantics for non-residential).';
COMMENT ON COLUMN public.units.tenant_contract_number IS 'Contract / lease number for non-residential tenants.';
COMMENT ON COLUMN public.units.tenant_lease_start   IS 'Lease start date for non-residential tenants.';
COMMENT ON COLUMN public.units.tenant_lease_end     IS 'Lease end date for non-residential tenants.';
COMMENT ON COLUMN public.units.tenant_monthly_payment_aed IS 'Monthly rent (AED) for non-residential tenants.';

-- ============================================================
-- 0014_delete_building_cascade.sql
-- ============================================================
-- Cascade-delete a building plus every dependent row in one transaction.
-- The FKs from invoices / visits / service_requests / resident_assignments
-- / amenity_bookings / unit_attachments → units don't ON DELETE CASCADE,
-- so a plain "DELETE FROM buildings" fails for any building that has
-- history. Walk the dependency tree here.
--
-- PMC-only: a non-PMC caller would just silently no-op via RLS, but we
-- gate up front so the UI gets a clear error.
CREATE OR REPLACE FUNCTION public.delete_building_cascade(p_building_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_role         text;
  v_unit_count   int;
  v_assignment_count int;
  v_invoice_count   int;
  v_visit_count     int;
  v_sr_count        int;
  v_attachment_count int;
  v_booking_count   int;
BEGIN
  v_role := COALESCE((auth.jwt() -> 'app_metadata' ->> 'role'), '');
  IF v_role <> 'pmc' THEN
    RAISE EXCEPTION 'Only PMC can delete buildings (role=%)', v_role;
  END IF;

  SELECT COUNT(*) INTO v_unit_count FROM public.units WHERE building_id = p_building_id;

  WITH unit_ids AS (SELECT id FROM public.units WHERE building_id = p_building_id),
       del_ra  AS (DELETE FROM public.resident_assignments WHERE unit_id IN (SELECT id FROM unit_ids) RETURNING 1)
  SELECT COUNT(*) INTO v_assignment_count FROM del_ra;

  WITH unit_ids AS (SELECT id FROM public.units WHERE building_id = p_building_id),
       del_i   AS (DELETE FROM public.invoices WHERE unit_id IN (SELECT id FROM unit_ids) RETURNING 1)
  SELECT COUNT(*) INTO v_invoice_count FROM del_i;

  WITH unit_ids AS (SELECT id FROM public.units WHERE building_id = p_building_id),
       del_v   AS (DELETE FROM public.visits WHERE unit_id IN (SELECT id FROM unit_ids) RETURNING 1)
  SELECT COUNT(*) INTO v_visit_count FROM del_v;

  WITH unit_ids AS (SELECT id FROM public.units WHERE building_id = p_building_id),
       del_sr  AS (DELETE FROM public.service_requests WHERE unit_id IN (SELECT id FROM unit_ids) RETURNING 1)
  SELECT COUNT(*) INTO v_sr_count FROM del_sr;

  WITH unit_ids AS (SELECT id FROM public.units WHERE building_id = p_building_id),
       del_ua  AS (DELETE FROM public.unit_attachments WHERE unit_id IN (SELECT id FROM unit_ids) RETURNING 1)
  SELECT COUNT(*) INTO v_attachment_count FROM del_ua;

  -- amenity_bookings has BOTH unit_id and building_id FKs — clear both.
  WITH unit_ids AS (SELECT id FROM public.units WHERE building_id = p_building_id),
       del_ab  AS (
         DELETE FROM public.amenity_bookings
         WHERE unit_id IN (SELECT id FROM unit_ids) OR building_id = p_building_id
         RETURNING 1
       )
  SELECT COUNT(*) INTO v_booking_count FROM del_ab;

  -- Building-level dependents.
  DELETE FROM public.vendor_buildings     WHERE building_id = p_building_id;
  DELETE FROM public.security_assignments WHERE building_id = p_building_id;
  DELETE FROM public.contracts            WHERE building_id = p_building_id;

  -- Now the units, then the building itself.
  DELETE FROM public.units      WHERE building_id = p_building_id;
  DELETE FROM public.buildings  WHERE id = p_building_id;

  RETURN jsonb_build_object(
    'units',       v_unit_count,
    'assignments', v_assignment_count,
    'invoices',    v_invoice_count,
    'visits',      v_visit_count,
    'srs',         v_sr_count,
    'attachments', v_attachment_count,
    'bookings',    v_booking_count
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.delete_building_cascade(uuid) TO authenticated;

COMMENT ON FUNCTION public.delete_building_cascade(uuid) IS
  'Cascade-delete a building and every dependent row (units, invoices, visits, service requests, resident assignments, amenity bookings, vendor links, security assignments, contracts). PMC-only.';

-- ============================================================
-- 0015_buildings_purchase_value.sql
-- ============================================================
-- Landlord-facing additions so yield + capital appreciation can be
-- computed at all. Today the buildings table has no acquisition data
-- so we can't tell whether an asset is performing well — only what's
-- currently being collected.
ALTER TABLE public.buildings
  ADD COLUMN IF NOT EXISTS purchase_price numeric,
  ADD COLUMN IF NOT EXISTS current_value  numeric,
  ADD COLUMN IF NOT EXISTS acquired_on    date;

COMMENT ON COLUMN public.buildings.purchase_price IS 'Purchase / acquisition price in AED. Used to compute gross + net yield.';
COMMENT ON COLUMN public.buildings.current_value  IS 'Current market value estimate in AED. Used to compute capital appreciation.';
COMMENT ON COLUMN public.buildings.acquired_on    IS 'Date the asset was acquired. Used for hold-period and ROI calculations.';
